### ISSUE TITLE
Iterating over DataArray ends in IO error

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/nixpy#147]
When iterating over a DataArray, the iteration doesn't stop at the end of the array's length and causes a read error.

The following code
```python
from __future__ import print_function
import nix

nixfile = nix.File.open("/tmp/foo.h5", nix.FileMode.Overwrite)
block = nixfile.create_block("ablock", "blocktype")
data_array = block.create_data_array("ada", "datatype", data=range(5))

print(len(data_array))
print(data_array[0])
print(data_array[4])
print(data_array[:2])

for value in data_array:
    print(value, end=", ")
```

creates the following output
```
5
0
4
[0 1]
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 140720079103744:
  #000: H5Dio.c line 161 in H5Dread(): selection+offset not within extent
    major: Dataspace
    minor: Out of range
0, 1, 2, 3, 4, Traceback (most recent call last):
  File "nix_da_error.py", line 13, in <module>
    for value in data_array:
  File "/home/achilleas/code/gnode/nixpy/nix/data_array.py", line 120, in __getitem__
    self._read_data(raw, count, offset)
RuntimeError: DataSet::read() IO error
```

**Comment by gicmo** [comment]
Ah, python, always great fun. `DataArray`s (or better `DataSet`s) don't actually explicitly support the iteration protocol (i.e. `__iter__`). Mostly because it is probably not a good idea to go down to the file for every single number. We have a `__len__` and `__getitem__` which I guess makes the range based for loop work. To make it fully work though we would have to throw a `IndexError` in the [DataSet](https://github.com/G-Node/nixpy/blob/master/nix/data_array.py#L112) I guess. A bit of overhead, but why not ...

**Comment by achilleas-k** [comment]
Is iteration over a `DataSet` something that is desirable? I only came across it for testing, when I needed to make sure values were written correctly.

**Comment by jgrewe** [comment]
methinks, this issue is solved?! Could someone confirm and close?

**Comment by gicmo** [comment]
Should be! ;)
