### ISSUE TITLE
file handling using context manager

### ISSUE THREAD

**Issue by JuliaSprenger** [G-Node/nixpy#310]
It would be nice if the following code would work:

```python
with nix.File.open(file_name, nix.FileMode.Overwrite) as file:
    file.create_block("test block", "test")
```

**Comment by achilleas-k** [comment]
I've thought about this before but it wouldn't really work for NIX, since the file needs to be open for the whole process of creating objects. Context managers are convenient for cases where you can do:
```python
things = create_things()
with openfile(name) as f:
    f.write_all_the_things(things)
```
but for NIXPy it would mean the whole file structure creation would have to be in the context.

It's not an issue to make it, I just don't really see the need for it.

I can add it if you think it would be useful.

**Comment by achilleas-k** [comment]
Yeah, I @JuliaSprenger described a few use cases and convinced me :)
