### ISSUE TITLE
Make nixpy compatible with python3

### ISSUE THREAD

**Issue by stoewer** [G-Node/nixpy#69]

**Comment by gicmo** [comment]
Pr #124 should have fixed most (all?) of this. Not sure what is missing.

**Comment by jgrewe** [comment]
isn't this issue solved? Compilation with python 3 works, tests, run...

**Comment by stoewer** [comment]
If this is the case I suggest to configure Travis (and maybe Appveyor) to run and build the tests for python 3 too and close this issue.

**Comment by stoewer** [comment]
I guess I was too fast, there is still the issue with the changes in the metaclass introduced in 984fecf385963008ce0f380e0bb45760a93a4c44 . This is really hacky and can be avoided.

**Comment by mpsonntag** [comment]
I'll try to configure Travis for Python 3 and come up with a solution for the metaclass changes until Thursday. If I can't come up with a nice solution, Adrian will then take over.

**Comment by gicmo** [comment]
@mpsonntag Cool! There is one thing. Currently we are building NIX from source for nixpy. Since we probably want travis to build, test both python 2 and 3 we would need to compile NIX two times. Quite a waste of time (and processing power). It would really be great if we could somehow 'reuse' the binary that has been build by travis for NIX; that or the ppa build of NIX. Or we look into [bintray](https://bintray.com), which is used by homebrew.  Since we are using the hdf5 that comes with travis, the hdf5 issue we had with binaries before should not be there anymore. Hopefully...
