### ISSUE TITLE
unidentified C++ exception when opening file twice in Overwrite mode

### ISSUE THREAD

**Issue by segensreich** [G-Node/nixpy#88]
```python
nix_file = nix.File.open('foo.h5', nix.FileMode.Overwrite)
nix_file = nix.File.open('foo.h5', nix.FileMode.Overwrite)
```
Does not happen with ReadWrite or ReadOnly. But happens with combination of the Read* and Overwrite.

**Comment by stoewer** [comment]
The current version of nix/nixpy now behaves like this:

```python
nix_file = nix.File.open('foo.h5', nix.FileMode.Overwrite)
nix_file = nix.File.open('foo.h5', nix.FileMode.Overwrite)
```

This throws a `RuntimeError` because an opened file is opened again with truncate mode. I think this is the correct behavior. Reopen a file with other open modes works, which is also OK.

To reopen a file with truncate mode it has to be closed properly. This can be done with `close`, or by assigning `None`:

```python
file = nix.File.open('foo.h5', nix.FileMode.Overwrite)
file = None
file = nix.File.open('foo.h5', nix.FileMode.Overwrite)
```

```python
file = nix.File.open('foo.h5', nix.FileMode.Overwrite)
file.close()
file = nix.File.open('foo.h5', nix.FileMode.Overwrite)
```

Therefore I suggest to close this issue as well as #78.

**Comment by jgrewe** [comment]
I cross-checked and agree to close this issue.
